# Generated by Django 4.2 on 2023-05-01 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_start_value', models.IntegerField()),
                ('pf_err', models.DecimalField(decimal_places=4, max_digits=19)),
                ('pf_risk', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_ugl', models.IntegerField()),
                ('total_rr', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6)),
                ('stock_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('startDate_close', models.IntegerField(null=True)),
                ('endDate_close', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('start_value', models.IntegerField(null=True)),
                ('end_value', models.IntegerField(null=True)),
                ('ugl', models.IntegerField(null=True)),
                ('return_rate', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info_stock_name', to='difi.stock_info')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info_ticker', to='difi.stock_info')),
            ],
        ),
        migrations.CreateModel(
            name='stock_ts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.IntegerField()),
                ('change', models.DecimalField(decimal_places=6, max_digits=19)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='difi.stock_info')),
            ],
        ),
    ]
