# Generated by Django 5.0.1 on 2024-02-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
