# Generated by Django 4.2 on 2023-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_info',
            name='ticker',
            field=models.TextField(),
        ),
    ]
