# Generated by Django 5.0.1 on 2024-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difi', '0002_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=1000),
        ),
    ]
