# Generated by Django 4.2 on 2023-05-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difi', '0002_alter_stock_info_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_ts',
            name='ticker',
            field=models.TextField(),
        ),
    ]
