# Generated by Django 4.2 on 2023-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difi', '0003_alter_stock_ts_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_value',
            name='stock_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='ticker',
            field=models.TextField(),
        ),
    ]
